services:
  local-producer-cluster:
    container_name: local-producer-cluster
    image: openmina/openmina:0.5.0
    entrypoint: ["openmina-node-testing", "scenarios-generate", "--name", "simulation-small-forever-real-time"]
    ports:
      - 11010:11010
      - 11012:11012
      - 11014:11014

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile_FE
      args:
        BUILD_CONFIGURATION: block_producers
    ports:
      - "8070:80"