services:
  local-producer-cluster:
    container_name: local-producer-cluster
    image: openmina/openmina:tx-pool-2
    environment:
      - RUST_BACKTRACE=1
    entrypoint: ["openmina-node-testing", "scenarios-generate", "--name", "simulation-small-forever-real-time"]
    ports:
      - 11010:11010
      - 11012:11012
      - 11014:11014

  frontend:
    container_name: frontend
    image: openmina/frontend:tx-pool-2-producer-demo
    # build:
    #   context: .
    #   dockerfile: Dockerfile_FE
    #   args:
    #     BUILD_CONFIGURATION: block_producers
    ports:
      - "8070:80"