services:
  local-producer-cluster:
    container_name: local-producer-cluster
    image: openmina/openmina:0.8.3
    environment:
      - RUST_BACKTRACE=1
    entrypoint: ["openmina-node-testing", "scenarios-generate", "--name", "simulation-small-forever-real-time"]
    ports:
      - 11010:11010
      - 11012:11012
      - 11014:11014

  frontend:
    container_name: frontend
    # TODO: remove `-producer-demo` suffix in the next release, not needed anymore
    image: openmina/frontend:0.8.3-producer-demo
    environment:
      OPENMINA_FRONTEND_ENVIRONMENT: block_producers
    ports:
      - "8070:80"