apiVersion: v1
kind: Service
metadata:
  name: debugger-service
spec:
  type: NodePort
  selector:
    app: debugger
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debugger
  name: debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugger
  template:
    metadata:
      labels:
        app: debugger
    spec:
      runtimeClassName: kata-clh
      containers:
        - name: bpf-debugger
          imagePullPolicy: Always
          image: openmina/mina-network-debugger:bc481a39
          securityContext:
            privileged: true
          command: ["sh", "-ce", "bpf-recorder"]
          env:
            - name: RUST_LOG
              value: "info"
            - name: SERVER_PORT
              value: "80"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /sys/kernel/debug
              name: sys-kernel-debug
            - mountPath: /proc
              name: proc
          resources:
            requests:
              memory: 16G
            limits:
              memory: 32G
        - name: openmina
          image: debian:buster
          command: ["sh", "-c"]
          args:
            - |
              apt-get update && apt-get -y install git curl gcc libssl-dev pkg-config
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              PATH=$PATH:~/.cargo/bin && rustup update nightly-2023-10-01
              git clone https://github.com/openmina/openmina
              cd openmina
              git fetch && git checkout feat/tests-with-debugger
              PATH=$PATH:~/.cargo/bin && cargo +nightly-2023-10-01 build --release --bin openmina 
              cp target/release/openmina /usr/local/bin/openmina
              openmina node -p 10000 --libp2p-port 8302
          ports:
            - name: external-ip
              containerPort: 8302
              protocol: TCP
            - name: node-server
              containerPort: 10000
              protocol: TCP
          env:
            - name: BPF_ALIAS
              value: "/coda/0.0.1/3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e-0.0.0.0"
          resources:
            requests:
              memory: 16G
            limits:
              memory: 32G
      volumes:
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: proc
          hostPath:
            path: /proc
---
