[package]
name = "mina-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
mina-signer = {git = "https://github.com/o1-labs/proof-systems", rev = "041f48f6f3f18bae3bbbe6ec06cfcd03d0e5ec8a"}
mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "041f48f6f3f18bae3bbbe6ec06cfcd03d0e5ec8a"}
oracle = {git = "https://github.com/o1-labs/proof-systems", rev = "041f48f6f3f18bae3bbbe6ec06cfcd03d0e5ec8a"}
mina-curves = {git = "https://github.com/o1-labs/proof-systems", rev = "041f48f6f3f18bae3bbbe6ec06cfcd03d0e5ec8a"}
o1-utils = {git = "https://github.com/o1-labs/proof-systems", rev = "041f48f6f3f18bae3bbbe6ec06cfcd03d0e5ec8a"}
bs58 = "0.4.0"
serde-binprot = { git = "https://github.com/name-placeholder/serde-binprot.git", branch = "ledger" }
# serde-binprot = {git = "https://github.com/LaurentMazare/serde-binprot.git", rev = "98daaf8f0f5dc57ea7bc69594d963b30e02e8485"}
serde = "1.0"

# oracle = { path = "../oracle" }
# mina-curves = { path = "../curves" }
# o1-utils = { path = "../utils" }

ark-ff = { version = "0.3.0", features = [ "parallel", "asm", "std" ] }
ark-serialize = { version = "0.3.0", features = [ "std" ] }

bitvec = "1.0.0"
hex = "0.4.3"

ocaml-interop = "0.8"
