[package]
name = "mina-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ledger"
path = "src/bin/ledger.rs"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

# For wasm on browser, add those flags:
# https://stackoverflow.com/a/73023306

[dependencies]
mina-signer = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
oracle = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
mina-curves = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
o1-utils = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
kimchi = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}

bs58 = "0.4.0"
mina-p2p-messages = { git = "https://github.com/name-placeholder/mina-p2p-messages-rs", features = ["hashing"] }
# mina-p2p-messages = { path = "/home/sebastien/github/mina-p2p-messages-rs", features = ["hashing"] }
# mina-p2p-messages = { path = "/tmp/mina-p2p-messages-rs", features = ["hashing"] }

binprot = { git = "https://github.com/name-placeholder/binprot-rs", rev = "ead5ba916725abf8ab212b89985b47c79d1a006a" }
binprot_derive = { git = "https://github.com/name-placeholder/binprot-rs", rev = "ead5ba916725abf8ab212b89985b47c79d1a006a" }

sha2 = "0.10"
base64 = "0.13"

# oracle = { path = "../oracle" }
# mina-curves = { path = "../curves" }
# o1-utils = { path = "../utils" }



# ark-ff-new = { git = "https://github.com/arkworks-rs/algebra.git", features = [ "parallel", "asm", "std" ], package = "ark-ff" }
# ark-serialize = { git = "https://github.com/arkworks-rs/algebra.git", features = [ "std" ] }

ark-ff = { version = "0.3.0", features = [ "parallel", "asm", "std" ] }
ark-serialize = { version = "0.3.0", features = [ "std" ] }
rayon = "1"

bitvec = "1.0.0"
hex = "0.4.3"
num-bigint = "0.4"

once_cell = "1"
rand = "0.8"
uuid = { version = "1", features = [ "v4" ] }

packed_simd = { version = "0.3", package = "packed_simd_2" }
backtrace = "0.3"
derive_more = "0.99.17"

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm_thread = { version = "0.2", features = [ "es_modules" ] }
wasm-bindgen = "0.2"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
# ocaml-interop = { path = "/home/sebastien/github/ocaml-interop" }
ocaml-interop = { git = "https://github.com/sebastiencs/ocaml-interop.git", branch = "closure-values-dbg" }
# ocaml-interop = { git = "https://github.com/tizoc/ocaml-interop.git", branch = "closure-values" }

[dev-dependencies]

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wasm-bindgen-test = "0.3.0"
web-sys = { version = "0.3", features = ["Blob", "DedicatedWorkerGlobalScope", "MessageEvent", "Url", "Worker", "WorkerType", "WorkerOptions", "console", "Window", "Performance" ] }

[features]
# Add this feature to run tests in both nodejs and browser:
# https://github.com/rustwasm/wasm-bindgen/issues/2571
in_nodejs = []

[profile.release]
debug = true
