name: Create Docker Compose Archives

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create versioned directory and package files
      run: |
        release_dir="openmina-${{ github.ref_name }}-docker-compose"
        mkdir -p "$release_dir"
        cp -r docker-compose.* README.md "$release_dir/"
        zip -r "${release_dir}.zip" "$release_dir"
        tar -czvf "${release_dir}.tar.gz" "$release_dir"

    - name: Create a GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: true
        prerelease: false

    - name: Upload the zip file as a release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: "openmina-${{ github.ref_name }}-docker-compose.zip"
        asset_path: "openmina-${{ github.ref_name }}-docker-compose.zip"
        asset_content_type: application/zip

    - name: Upload the tarball as a release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: "openmina-${{ github.ref_name }}-docker-compose.tar.gz"
        asset_path: "openmina-${{ github.ref_name }}-docker-compose.tar.gz"
        asset_content_type: application/gzip
